"""Initial migration.

Revision ID: 8933c82c42fc
Revises: 
Create Date: 2023-03-01 16:48:20.606763

"""
from datetime import datetime
from alembic import op
import bcrypt
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8933c82c42fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('full_name', sa.String(length=192), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )

    op.bulk_insert(user_table, [{"user":"admin@test.com", "password":bcrypt.hashpw(
                "12345678".encode('utf-8'), bcrypt.gensalt()).decode('utf-8'), "full_name":"John Smith", "deleted": False, "date_created": datetime.now(), "date_modified": datetime.now()}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
